### ISSUE TITLE
Anilist login bug

### ISSUE THREAD

**Issue by HoboSamurai** [jerry08/Anikin#31]
### Summary

Logging into anilist goes back to app, but not logged in

### Steps to reproduce

Launch anikin
Log in to anilist through anikin
No profit :(
Try again
In app browser launches for brief second before closing back to app, still not logged in

### Expected Result

Log in

### Actual Result

Weird bug where log in browser opens, then closes for unknown time, after a day or two it opens to log in page again

### Device Information

Android 14 
Anikin 2.0.3

### Checklist

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have made sure that that this bug is reproducible on the latest version of the application.
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible.

### Additional Information

Once "logged in" the app shows the same screen, although I can have favorites they are not saved anywhere, other than just having a heart next to them once searched.

When I try to relog in, it only opens and closes the browser in a quick succussion, after a few hours to a day it normally fixes, and I can attempt a log in, only to be right back.

**Comment by Huzzu-BCMW** [comment]
Yeah, it doesn't work in mine too. The EXACT SAME errors.

**Comment by jerry08** [comment]
This is not a bug. When the browser closes after you login to Anilist, you are logged into your account and the only thing you can do is save your favorites which will update your Anilist favorites. Since this app is still a work in progress, there is no indication to show that the user is logged in. The settings screen will soon be updated to show your user icon and there'll be added Anilist functionality.
